# Welcome to Amplified for Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Human, all too human
email: buildrush@naver.com
description: >
  Better structure, much more effective way.
logo: "/assets/images/logo.jpg"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.decorus.io" # the base hostname & protocol for your site
paginate:	10 # The number of posts to show per page on your homepage

name: 'Yongwoo Lee'
bio: >
  Backend developer in south korea. using PHP, Javascript and bunch of other things.
author_image: "/assets/images/author.jpg"
twitter_username:
github_username: FOKKIA

# Google Analytics
analytics_id: "UA-112777515-1"

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  parse_block_html: true
  input: GFM
  syntax_highlighter: rouge

timezone: '+0900'
gems:
  - jekyll-paginate
